
DefaultPlayerModels = {
	["models/player/alyx.mdl"] = true,
	["models/player/barney.mdl"] = true,
	["models/player/breen.mdl"] = true,
	["models/player/charple.mdl"] = true,
	["models/player/p2_chell.mdl"] = true,
	["models/player/corpse1.mdl"] = true,
	["models/player/combine_soldier.mdl"] = true,
	["models/player/combine_soldier_prisonguard.mdl"] = true,
	["models/player/combine_super_soldier.mdl"] = true,
	["models/player/eli.mdl"] = true,
	["models/player/gman_high.mdl"] = true,
	["models/player/kleiner.mdl"] = true,
	["models/player/monk.mdl"] = true,
	["models/player/mossman.mdl"] = true,
	["models/player/mossman_arctic.mdl"] = true,
	["models/player/odessa.mdl"] = true,
	["models/player/police.mdl"] = true,
	["models/player/police_fem.mdl"] = true,
	["models/player/magnusson.mdl"] = true,
	["models/player/soldier_stripped.mdl"] = true,
	["models/player/zombie_classic.mdl"] = true,
	["models/player/zombie_fast.mdl"] = true,
	
	-- Citizens
	["models/player/Group01/male_01.mdl"] = true,
	["models/player/Group01/male_02.mdl"] = true,
	["models/player/Group01/male_03.mdl"] = true,
	["models/player/Group01/male_04.mdl"] = true,
	["models/player/Group01/male_05.mdl"] = true,
	["models/player/Group01/male_06.mdl"] = true,
	["models/player/Group01/male_07.mdl"] = true,
	["models/player/Group01/male_08.mdl"] = true,
	["models/player/Group01/male_09.mdl"] = true,
	["models/player/Group01/female_01.mdl"] = true,
	["models/player/Group01/female_02.mdl"] = true,
	["models/player/Group01/female_03.mdl"] = true,
	["models/player/Group01/female_04.mdl"] = true,
	["models/player/Group01/female_05.mdl"] = true,
	["models/player/Group01/female_06.mdl"] = true,
	
	-- Refugees
	["models/player/Group03/male_01.mdl"] = true,
	["models/player/Group03/male_02.mdl"] = true,
	["models/player/Group03/male_03.mdl"] = true,
	["models/player/Group03/male_04.mdl"] = true,
	["models/player/Group03/male_05.mdl"] = true,
	["models/player/Group03/male_06.mdl"] = true,
	["models/player/Group03/male_07.mdl"] = true,
	["models/player/Group03/male_08.mdl"] = true,
	["models/player/Group03/male_09.mdl"] = true,
	["models/player/Group03/female_01.mdl"] = true,
	["models/player/Group03/female_02.mdl"] = true,
	["models/player/Group03/female_03.mdl"] = true,
	["models/player/Group03/female_04.mdl"] = true,
	["models/player/Group03/female_05.mdl"] = true,
	["models/player/Group03/female_06.mdl"] = true,
	
	["models/player/Group02/male_02.mdl"] = true,
	["models/player/Group02/male_04.mdl"] = true,
	["models/player/Group02/male_06.mdl"] = true,
	["models/player/Group02/male_08.mdl"] = true,
	
	-- Medics
	["models/player/Group03m/male_01.mdl"] = true,
	["models/player/Group03m/male_02.mdl"] = true,
	["models/player/Group03m/male_03.mdl"] = true,
	["models/player/Group03m/male_04.mdl"] = true,
	["models/player/Group03m/male_05.mdl"] = true,
	["models/player/Group03m/male_06.mdl"] = true,
	["models/player/Group03m/male_07.mdl"] = true,
	["models/player/Group03m/male_08.mdl"] = true,
	["models/player/Group03m/male_09.mdl"] = true,
	["models/player/Group03m/female_01.mdl"] = true,
	["models/player/Group03m/female_02.mdl"] = true,
	["models/player/Group03m/female_03.mdl"] = true,
	["models/player/Group03m/female_04.mdl"] = true,
	["models/player/Group03m/female_05.mdl"] = true,
	["models/player/Group03m/female_06.mdl"] = true,
	
	["models/player/skeleton.mdl"] = true,
	["models/player/zombie_soldier.mdl"] = true,
	["models/player/hostage/hostage_01.mdl"] = true,
	["models/player/hostage/hostage_02.mdl"] = true,
	["models/player/hostage/hostage_03.mdl"] = true,
	["models/player/hostage/hostage_04.mdl"] = true,
	["models/player/arctic.mdl"] = true,
	["models/player/gasmask.mdl"] = true,
	["models/player/guerilla.mdl"] = true,
	["models/player/leet.mdl"] = true,
	["models/player/phoenix.mdl"] = true,
	["models/player/riot.mdl"] = true,
	["models/player/swat.mdl"] = true,
	["models/player/urban.mdl"] = true,
	["models/player/dod_german.mdl"] = true,
	["models/player/dod_american.mdl"] = true
	
}