
# Bodygroup Names
eps.model_bg.empty=Vide
eps.model_bg.pants=Pantalons
eps.model_bg.jeans=Jeans
eps.model_bg.tshirt=T-shirt
eps.model_bg.shirt=Chemise
eps.model_bg.blouse=Blouse
eps.model_bg.jacket=Veste
eps.model_bg.coat=Manteau
eps.model_bg.sweater=Chandail
eps.model_bg.hoodie=Chandail à capuchon
eps.model_bg.nightshirt=Chemise de nuit
eps.model_bg.hoodcloth=Capot
eps.model_bg.blouson=Blouson
eps.model_bg.brooch=Broche
eps.model_bg.jewelry=Bijoux
eps.model_bg.cufflink=Bouton de manchette
eps.model_bg.pendant=During
eps.model_bg.tanktop=Haut sans manches
eps.model_bg.leatherjacket=Veste en cuir
eps.model_bg.shorts=Pantalons court
eps.model_bg.pantsu=Culotte
eps.model_bg.mask=Masque
eps.model_bg.stockings=Bas
eps.model_bg.stocking=Bas
eps.model_bg.hose=Tuyau
eps.model_bg.skirt=Jupe
eps.model_bg.dress=Robe
eps.model_bg.cloak=Cape
eps.model_bg.suit=Combination
eps.model_bg.badges=Insignes
eps.model_bg.blazer=Veste de costume
eps.model_bg.aodai=Áo dài
eps.model_bg.beret=Béret
eps.model_bg.fedora=Fedora
eps.model_bg.cowboyboots=Bottes de cowboy
eps.model_bg.seashell=Coquillage
eps.model_bg.bathingsuit=Maillot de bain
eps.model_bg.swimwear=Maillot de bain
eps.model_bg.boafur=Boa
eps.model_bg.wallet=Portefeuille
eps.model_bg.piercing=Perçage
eps.model_bg.earpiercing=Perçage des oreilles
eps.model_bg.nosepiercing=Perçage de nez
eps.model_bg.bathingattire=Tenue de bain
eps.model_bg.cowboyhat=Chapeau de cowboy
eps.model_bg.cravat=Cravate
eps.model_bg.clothingbutton=Bouton
eps.model_bg.academicdress=Tenue académique
eps.model_bg.kaftan=Caftan
eps.model_bg.caftan=Caftan
eps.model_bg.corset=Corset
eps.model_bg.vest=Gilet
eps.model_bg.hookeye=Crochet et œillet
eps.model_bg.garb=Tenue
eps.model_bg.bead=Perle
eps.model_bg.prayerbeads=Chapelet
eps.model_bg.crown=Couronne
eps.model_bg.brassiere=Soutien-gorge
eps.model_bg.fez=Fez
eps.model_bg.leggings=Leggings
eps.model_bg.trousers=Pantalon
eps.model_bg.worrybeads=Chapelet de souci
eps.model_bg.slacks=Pantalon
eps.model_bg.overalls=Salopettes  
eps.model_bg.scarf=Foulard
eps.model_bg.gloves=Gants
eps.model_bg.stuffedtoy=Jouet en peluche
eps.model_bg.stuffedanimal=Peluche
eps.model_bg.toydoll=Poupée
eps.model_bg.toy=Jouet
eps.model_bg.wing=Ailes
eps.model_bg.wristband=Bracelet
eps.model_bg.wristribbon=Ruban pour poignet
eps.model_bg.rag.doll=Poupée en chiffon
eps.model_bg.sewingneedle=Aiguille à coudre
eps.model_bg.needle=Aiguille
eps.model_bg.plushie=Peluche
eps.model_bg.hat=Chapeau
eps.model_bg.bonnet=Bonnet
eps.model_bg.outfit=Tenue
eps.model_bg.tiara=Tiare
eps.model_bg.sunhat=Chapeau de soleil
eps.model_bg.parka=Parka
eps.model_bg.cap=Casquette
eps.model_bg.tights=Collants
eps.model_bg.blacktieattire=Cravate noire
eps.model_bg.whitetieattire=Cravate blanche
eps.model_bg.fulleveningd=Tenue de soirée
eps.model_bg.tux=Tux
eps.model_bg.tuxedo=Tuxedo
eps.model_bg.dinnersuit=Tenue de dîner
eps.model_bg.sash=Bande
eps.model_bg.beanie=Tuque
eps.model_bg.socks=Bas
eps.model_bg.shoes=Souliers
eps.model_bg.sneakers=Baskets
eps.model_bg.boots=Bottes
eps.model_bg.sandals=Sandales
eps.model_bg.diaper=Couche
eps.model_bg.flipflops=Tongs
eps.model_bg.underwear=Sous-vêtements
eps.model_bg.boxers=Boxeurs
eps.model_bg.briefs=Culottes
eps.model_bg.bra=Soutien-gorge
eps.model_bg.quiltedjacket=Veste matelassée
eps.model_bg.hairtie=Élastique à cheveux
eps.model_bg.bangshair=Frange
eps.model_bg.fringehair=Fringe
eps.model_bg.lingerie=Lingerie
eps.model_bg.badge=Badge
eps.model_bg.visor=Visière
eps.model_bg.panties=Culottes
eps.model_bg.cape=Cape
eps.model_bg.pantyhose=Collants
eps.model_bg.accessoryshort=Acc
eps.model_bg.accessory=Accessoire
eps.model_bg.halo=Halo
eps.model_bg.pen=Stylo
eps.model_bg.pencil=Crayon
eps.model_bg.backpack=Sac à dos
eps.model_bg.paintbrush=Pinceau
eps.model_bg.nightgown=Chemise de nuit
eps.model_bg.cardigan=Cardigan
eps.model_bg.pajamas=Pyjama
eps.model_bg.cummerbund=Ceinture plissée
eps.model_bg.robe=Robe
eps.model_bg.veil=Voile
eps.model_bg.umbrella=Parapluie
eps.model_bg.bandanna=Bandana
eps.model_bg.bandana=Bandana
eps.model_bg.kerchief=Foulard
eps.model_bg.sweatshirt=Chandail
eps.model_bg.tunic=Tunique
eps.model_bg.apron=Tablier
eps.model_bg.swimsuit=Maillot de bain
eps.model_bg.waistcoat=Gilet
eps.model_bg.toga=Toge
eps.model_bg.bikini=Bikini
eps.model_bg.trunks=Maillots
eps.model_bg.activewear=Vêtements de sport
eps.model_bg.sportswear=Vêtements de sport
eps.model_bg.gilet=Gilet
eps.model_bg.uniform=Uniforme
eps.model_bg.tracksuit=Survêtement
eps.model_bg.yogapants=Pantalon de yoga
eps.model_bg.wig=Perruque
eps.model_bg.raincoat=Imperméable
eps.model_bg.wegown=Robe de mariée
eps.model_bg.mittens=Moufles
eps.model_bg.horns=Cornes
eps.model_bg.horn=Corne
eps.model_bg.demonhorn=Corne du démon
eps.model_bg.demonhorns=Cornes du démon
eps.model_bg.demontail=Queue du démon
eps.model_bg.hairtails=Queues de cheveux

# All possibilities for ear category (Do not think it as only plural/singular difference when translating)

eps.model_bg.catears=Oreilles de chat
eps.model_bg.foxears=Oreilles de renard
eps.model_bg.bunnyears=Oreilles de lapin
eps.model_bg.dogears=Oreilles de chien
eps.model_bg.nekoears=Oreilles de neko

eps.model_bg.catear=Oreille de chat
eps.model_bg.foxear=Oreille de renard
eps.model_bg.bunnyear=Oreille de lapin
eps.model_bg.dogear=Oreille de chien
eps.model_bg.nekoear=Oreille de neko

eps.model_bg.cat_ear=Oreille de chat
eps.model_bg.fox_ear=Oreille de renard
eps.model_bg.bunny_ear=Oreille de lapin
eps.model_bg.dog_ear=Oreille de chien
eps.model_bg.neko_ear=Oreille de neko

eps.model_bg.cat_ears=Oreilles de chat
eps.model_bg.fox_ears=Oreilles de renard
eps.model_bg.bunny_ears=Oreilles de lapin
eps.model_bg.dog_ears=Oreilles de chien
eps.model_bg.neko_ears=Oreilles de neko

eps.model_bg.earmuffs=Cache-oreilles
eps.model_bg.poloshirt=Chandail polo
eps.model_bg.collarribbon=Ruban pour collier
eps.model_bg.clothesflower=Vêtement fleur
eps.model_bg.clothesribbon=Ruban pour vêtements
eps.model_bg.dressflower=Robe fleur
eps.model_bg.kasaya=Kasaya
eps.model_bg.belt=Ceinture
eps.model_bg.tie=Cravate
eps.model_bg.bustier=Bustier
eps.model_bg.camisole=Camisole
eps.model_bg.sleeve=Manche
eps.model_bg.bowtie=Noeux papillon
eps.model_bg.choker=Collier ras du cou
eps.model_bg.bow_cloth=Noeux
eps.model_bg.hairshadow=Ombre de cheveux
eps.model_bg.hairshadows=Ombres de cheveux
eps.model_bg.claws=Griffes
eps.model_bg.coatfur=Fourrure de manteau
eps.model_bg.headphones=Écouteur
eps.model_bg.jacketfur=Veste en fourrure
eps.model_bg.ponytailhair=Queue de cheval
eps.model_bg.eyebrows=Sourcils
eps.model_bg.legbelt=Ceinture pour jambe
eps.model_bg.flower=Fleur
eps.model_bg.flowers=Fleurs
eps.model_bg.rabbit_plushie=Peluche de lapin
eps.model_bg.rabbit=Lapin
eps.model_bg.bunny_plushie=Lapin
eps.model_bg.cat_plushie=Chat
eps.model_bg.shark_plushie=Requin
eps.model_bg.dog_plushie=Chien
eps.model_bg.mouth=Bouche
eps.model_bg.tongue=Langue
eps.model_bg.fox_plushie=Renard
eps.model_bg.watch=Montre
eps.model_bg.bracelet=Bracelet
eps.model_bg.collar=Collier
eps.model_bg.necklace=Collier
eps.model_bg.ring=Bague
eps.model_bg.glasses=Lunettes
eps.model_bg.blush=Rougir
eps.model_bg.sunglasses=Lunettes de soleil
eps.model_bg.innerwear=Sous-vêtements
eps.model_bg.knapsack=Sac à dos
eps.model_bg.schoolbag=Sac à dos (scolaire)
eps.model_bg.rucksack=Sac à dos
eps.model_bg.pack=Paquet
eps.model_bg.topclothbralevel=Haut
eps.model_bg.booksack=Sac à dos
eps.model_bg.bookbag=Sac à dos
eps.model_bg.hairclip=Clip
eps.model_bg.hairclip2=Barrette
eps.model_bg.hairstyle=Coiffure
eps.model_bg.pouches=Sacs
eps.model_bg.hairbuns=Chignons
eps.model_bg.hairbun=Chignon
eps.model_bg.hairbun2=Petit pain
eps.model_bg.tag=Étiquette
eps.model_bg.hair=Cheveux
eps.model_bg.eyes=Yeux
eps.model_bg.ear=Oreille
eps.model_bg.ears=Oreilles
eps.model_bg.nose=Nez
eps.model_bg.tail=Queue

eps.model_bg.wings=Ailes
eps.model_bg.ribbon=Ruban
eps.model_bg.armband=Brassard
eps.model_bg.armbands=Brassards
eps.model_bg.top=Haut
eps.model_bg.shoe=Souliers
eps.model_bg.right_shoe=Soulier droite
eps.model_bg.left_shoe=Soulier gauche

eps.model_bg.dragon_horns=Cornes de dragon
eps.model_bg.dragon_tails=Queue de dragon
eps.model_bg.dragon_wings=Ailes de dragon

eps.model_bg.dragon_horn=Corne de dragon
eps.model_bg.dragon_tail=Queue de dragon
eps.model_bg.dragon_wing=Aile de dragon
eps.model_bg.rat=Rat

eps.model_bg.top_acc=Haut Acc
eps.model_bg.emotions=Émotions
eps.model_bg.emotion=Émotion

eps.model_bg.body_outline=Contour du corps
eps.model_bg.body.outline=Contour du corps
eps.model_bg.bodyoutline=Contour du corps

eps.model_bg.hood=Capot
eps.model_bg.bag=Sac
eps.model_bg.headband=Bandeau
eps.model_bg.hairband=Bandeau
eps.model_bg.glove=Gant
eps.model_bg.cloth=Tissu
eps.model_bg.clothes=Vêtements

eps.model_bg.ear_right=Oreille droite
eps.model_bg.ear_left=Oreille gauche
eps.model_bg.face=Visage

# Emotions

eps.model_bg.anger=Colère
eps.model_bg.sweat=Sueur
eps.model_bg.tired=Fatigué
eps.model_bg.shocked=Choqué
eps.model_bg.happy=Heureux
eps.model_bg.sad=Triste
eps.model_bg.scared=Peur
eps.model_bg.surprised=Surpris
eps.model_bg.excited=Excité
eps.model_bg.jealous=Jaloux
eps.model_bg.curious=Curieux
eps.model_bg.smirk=Sourire en coin
eps.model_bg.smile=Sourire

# Weapons
# Yes, weapons can be used and are used as bodygroups. Even HL2 weapons in some cases.

eps.model_bg.sword=Épée
eps.model_bg.longsword=Épée longue
eps.model_bg.claymore=Épée claymore
eps.model_bg.shield=Bouclier
eps.model_bg.spear=Lance
eps.model_bg.gun=Fusil
eps.model_bg.weapon=Arme
eps.model_bg.shamshir=Shamshir
eps.model_bg.saber=Sabre
eps.model_bg.yatagan=Yatagan
eps.model_bg.dagger=Dague
eps.model_bg.knife=Couteau
eps.model_bg.trident=Trident

eps.model_bg.357=Magnum .357
eps.model_bg.alyxgun=Fusil d'Alyx
eps.model_bg.annabelle=Annabelle
eps.model_bg.ar2=Fusil à impulsion
eps.model_bg.bugbait=Appât pour insectes
eps.model_bg.citizenpackage=Ration alimentaire
eps.model_bg.citizensuitcase=Vasile
eps.model_bg.crossbow=Arbalète
eps.model_bg.crowbar=Pied-de-biche
eps.model_bg.frag=Grenade à fragmentation
eps.model_bg.physcannon=Fusil de gravité
eps.model_bg.pistol=Pistolet 9mm
eps.model_bg.rpg=Lanceur RPG
eps.model_bg.shotgun=Fusil de chasse
eps.model_bg.slam=S.L.A.M.
eps.model_bg.smg1=Mitraillette
eps.model_bg.stunstick=Matraque électrique
eps.model_bg.oldmanharpoon=Harpon
eps.model_bg.gmod_camera=Caméra
eps.model_bg.gmod_tool=Pistolet à outils
eps.model_bg.manhack_welder=Pistolet Manhack
eps.model_bg.fists=Poings
eps.model_bg.flechettegun=Pistolet à fléchettes
eps.model_bg.medkit=Trousse de soins
eps.model_bg.physgun=Pistolet de physique

eps.model_bg.weapon_357=Magnum .357
eps.model_bg.weapon_alyxgun=Fusil d'Alyx
eps.model_bg.weapon_annabelle=Annabelle
eps.model_bg.weapon_ar2=Fusil à implusion
eps.model_bg.weapon_bugbait=Appât pour insectes
eps.model_bg.weapon_citizenpackage=Ration alimentaire
eps.model_bg.weapon_citizensuitcase=Valise
eps.model_bg.weapon_crossbow=Arbalète
eps.model_bg.weapon_crowbar=Pied-de-biche
eps.model_bg.weapon_frag=Grenade à fragmentation
eps.model_bg.weapon_physcannon=Fusil à gravité
eps.model_bg.weapon_pistol=Pistolet 9 mm
eps.model_bg.weapon_rpg=Lanceur RPG
eps.model_bg.weapon_shotgun=Fusil de chasse
eps.model_bg.weapon_slam=S.L.A.M.
eps.model_bg.weapon_smg1=Mitraillette
eps.model_bg.weapon_stunstick=Matraque électrique
eps.model_bg.weapon_oldmanharpoon=Harpon
eps.model_bg.weapon_fists=Poings
eps.model_bg.weapon_flechettegun=Fusil à fléchette
eps.model_bg.weapon_medkit=Trousse de soins
eps.model_bg.weapon_physgun=Pistolet à physique
